// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiResponse<T> =
  | { status: 'ok'; data: T }
  | { status: 'error'; error: string; message: string; code: number }
