// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-job retry backoff shape. Jitter is always applied on top (mandatory), so a
 * distributed fleet does not re-hit a recovering dependency in lockstep.
 */
export type BackoffStrategy = "fixed" | "exponential" | "fibonacci";
