// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserRole } from "./UserRole";

export type CreateUserRequest = { username: string, password: string, role: UserRole, 
/**
 * The tenant to place the user in. Honored only for a system admin (`None` =
 * a system-scoped user). A tenant admin always creates within their own tenant.
 */
tenantId: string | null, };
