// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Create or replace a secret. The value is write-only: it is encrypted on the way in
 * and never returned by any endpoint.
 */
export type CreateSecretRequest = { name: string, value: string, };
