// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Create a tenant (system admin only).
 */
export type CreateTenantRequest = { name: string, };
