// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MisfirePolicy } from "./MisfirePolicy";

export type CreateJobRequest = { name: string, schedule_cron: string | null, command: string, max_concurrency: number | null, misfire_policy: MisfirePolicy | null, };
