// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MisfirePolicy } from "./MisfirePolicy";
import type { RetryConfig } from "./RetryConfig";
import type { RunnerConfig } from "./RunnerConfig";

export type CreateJobRequest = { name: string, scheduleCron: string | null, runnerConfig: RunnerConfig, maxConcurrency: number | null, misfirePolicy: MisfirePolicy | null, 
/**
 * Optional retry policy (defaults to no retry).
 */
retry: RetryConfig | null, 
/**
 * Optional initial environment variables for the job's runner.
 */
env: { [key in string]?: string } | null, };
