// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DbEngine } from "./DbEngine";

/**
 * Create a shared DB connection config. `passwordSecret` is a `secret:<name>` reference,
 * not a plaintext password.
 */
export type CreateDbConfigRequest = { engine: DbEngine, name: string, host: string, port: number, username: string, passwordSecret: string, database: string, };
