// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A database engine a shared connection config targets. The string form
 * (`pgsql`/`mysql`) matches the runner type and selects the backing table.
 */
export type DbEngine = "pgSql" | "mySql";
