// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExecutableConfigSnapshotMeta =
  | {
      type: 'shell'
      command: string
      workingDir: string | null
      env: { [key in string]?: string }
    }
  | {
      type: 'pgSql'
      host: string
      port: number
      username: string
      passwordSecret: string
      database: string
      query: string
      timeoutSec: number | null
    }
  | {
      type: 'mySql'
      host: string
      port: number
      username: string
      passwordSecret: string
      database: string
      query: string
      timeoutSec: number | null
    }
  | {
      type: 'http'
      method: string
      url: string
      headers: { [key in string]?: string }
      body: string | null
      timeoutSec: number | null
    }
  | {
      type: 'node'
      module: string
      functionName: string
      timeoutSec: number | null
      env: { [key in string]?: string }
    }
  | {
      type: 'python'
      module: string
      className: string
      timeoutSec: number | null
      env: { [key in string]?: string }
    }
