// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobRunState } from "./JobRunState";

export type JobRun = { id: string, job_id: string, scheduled_for: string, state: JobRunState, worker_id: string | null, exit_code: number | null, started_at: string | null, finished_at: string | null, command: string, };
