// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutableConfigSnapshot } from './ExecutableConfigSnapshot'
import type { JobRunState } from './JobRunState'

export type JobRun = {
  id: string
  jobId: string
  scheduledFor: string
  state: JobRunState
  workerId: string | null
  exitCode: number | null
  startedAt: string | null
  finishedAt: string | null
  snapshot: ExecutableConfigSnapshot | null
  output: string | null
  errorOutput: string | null
}
