// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MisfirePolicy } from "./MisfirePolicy";

export type JobSpec = { id: string, name: string, schedule_cron: string | null, enabled: boolean, command: string, max_concurrency: number, misfire_policy: MisfirePolicy, };
