// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackoffStrategy } from "./BackoffStrategy";
import type { MisfirePolicy } from "./MisfirePolicy";
import type { RunnerConfig } from "./RunnerConfig";

export type JobSpec = { id: string, name: string, scheduleCron: string | null, enabled: boolean, runnerCfg: RunnerConfig, maxConcurrency: number, misfirePolicy: MisfirePolicy, 
/**
 * Retry config. `max_attempts = 1` means no retry. A `retryable` run is requeued
 * with a backoff (jittered) until attempts are exhausted, then it fails.
 */
maxAttempts: number, backoffStrategy: BackoffStrategy, backoffBaseSecs: number, backoffCapSecs: number, };
