// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MisfirePolicy } from "./MisfirePolicy";
import type { RunnerConfig } from "./RunnerConfig";

export type JobSpec = { id: string, name: string, scheduleCron: string | null, enabled: boolean, runnerCfg: RunnerConfig, maxConcurrency: number, misfirePolicy: MisfirePolicy, };
