// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogStream } from "./LogStream";

/**
 * One append-only chunk of a run attempt's captured output. Ordered within an attempt by
 * `seq` (assigned by the worker, which owns the running run, so it is a single writer).
 */
export type LogChunk = { seq: bigint, stream: LogStream, content: string, createdAt: string, };
