// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Size summary of a run attempt's log, so a reader can decide whether to load it whole or
 * page it.
 */
export type LogSize = { totalBytes: bigint, chunkCount: bigint, maxSeq: bigint | null, };
