// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which output stream a log chunk came from.
 */
export type LogStream = "stdout" | "stderr";
