// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MisfirePolicy = "skip" | { "run_if_late_within": [number, number] } | "run_immediately" | "coalesce" | "run_all";
