// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A registered node's key and its KEK-approval status. `publicKey` is hex (it is public,
 * safe to show, and lets an admin verify the fingerprint out of band before approving).
 */
export type NodeKeyResponse = { nodeId: string, keyVersion: number, status: string, publicKey: string, createdAt: string, approvedAt: string | null, };
