// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PruneRunsQuery = { 
/**
 * Delete terminal runs older than this many days (default 30).
 */
olderThanDays?: number, };
