// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The classification a runner reports for a finished attempt, distinct from the
 * process `exit_code` and the lifecycle `state`. `Retryable` asks the scheduler to
 * requeue the run (up to the job's `max_attempts`).
 */
export type ResultStatus = "success" | "failed" | "retryable";
