// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackoffStrategy } from "./BackoffStrategy";

/**
 * Per-job retry configuration. `Default` = no retry (`max_attempts = 1`).
 */
export type RetryConfig = { maxAttempts: number, backoffStrategy: BackoffStrategy, backoffBaseSecs: number, backoffCapSecs: number, };
