// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A snapshot of KEK rotation progress. `phase` is one of `idle`, `distributing`,
 * `rewrapping`, `done`. On a single node a rotation returns `done` immediately; on a
 * cluster it may report `distributing` while waiting for other nodes to ack the new key.
 */
export type RotateKekResponse = { phase: string, targetVersion: number | null, nodesAcked: number, nodesTotal: number, secretsRewrapped: number, secretsTotal: number, };
