// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The result of a KEK rotation: the new active KEK version every secret is now wrapped
 * under.
 */
export type RotateKekResponse = { kekVersion: number, };
