// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Paginated read of a run's log chunks. `after` reads forward from a cursor (catch up to
 * live), `before` reads the newest chunks below a seq (tail, then page earlier). With
 * neither, the latest `limit` chunks are returned (the tail).
 */
export type RunLogQuery = { after?: bigint, before?: bigint, limit?: number, };
