// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogChunk } from "./LogChunk";
import type { LogSize } from "./LogSize";

/**
 * A page of a run's log chunks plus the overall size, so the client can decide whether to
 * page further (load earlier or follow newer).
 */
export type RunLogPage = { chunks: Array<LogChunk>, size: LogSize, };
