// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Secret metadata. Deliberately carries no ciphertext or plaintext: secret values are
 * write-only and never leave the server.
 */
export type SecretMetaResponse = { id: string, name: string, kekVersion: number, createdAt: string, updatedAt: string, };
