// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Replace a job's environment variables (replace-all).
 */
export type SetJobEnvRequest = { env: { [key in string]?: string }, };
