// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A runtime, admin-settable configuration entry. Values are opaque strings;
 * consumers parse them (with a static-config default fallback) at use-time.
 */
export type Setting = { key: string, value: string, };
