// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SharedConfigMeta } from "./SharedConfigMeta";

export type SharedConfig = { name: string, meta: SharedConfigMeta, };
