// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SharedConfigMeta = { "type": "shell", env: Array<[string, string]>, } | { "type": "pgSql", host: string, port: number, username: string, passwordSecret: string, database: string, } | { "type": "mySql", host: string, port: number, username: string, passwordSecret: string, database: string, };
