// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DbEngine } from "./DbEngine";

/**
 * A shared database connection config, referenced by pgsql/mysql runners via id. The
 * password is held as a secret reference (`secret:<name>`) resolved at execution, never
 * as plaintext.
 */
export type SharedDbConfig = { id: string, engine: DbEngine, name: string, host: string, port: number, username: string, 
/**
 * A `secret:<name>` reference for the connection password. Never plaintext.
 */
passwordSecret: string, database: string, tenantId: string, };
