// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A tenant: the unit of data isolation. Jobs, secrets, and configs belong to one.
 */
export type Tenant = { id: string, name: string, createdAt: string, };
