// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Update a shared DB connection config. Absent fields are left unchanged. The engine is
 * fixed at create time and not editable.
 */
export type UpdateDbConfigRequest = { name: string | null, host: string | null, port: number | null, username: string | null, passwordSecret: string | null, database: string | null, };
