// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MisfirePolicy } from './MisfirePolicy'
import type { RunnerConfig } from './RunnerConfig'

export type UpdateJobRequest = {
  name: string | null
  scheduleCron: string | null | null
  runnerConfig: RunnerConfig | null
  maxConcurrency: number | null
  misfirePolicy: MisfirePolicy | null
}
