// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MisfirePolicy } from "./MisfirePolicy";

export type UpdateJobRequest = { name: string | null, schedule_cron: string | null | null, command: string | null, max_concurrency: number | null, misfire_policy: MisfirePolicy | null, };
