// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserRole } from "./UserRole";

export type User = { id: string, username: string, role: UserRole, 
/**
 * Scope: `None` = system-wide (all tenants), `Some(id)` = that tenant only.
 */
tenantId: string | null, createdAt: string, };
